### ISSUE TITLE
anyone succeeded with this garbage?

### ISSUE THREAD

**Issue by zxfrank** [globalpayments/globalpayments-woocommerce#10]
no vendor/autoload, no composer.json how the f are we supposed to install this piece of s?

**Comment by zxfrank** [comment]
Used https://github.com/senthilkumar-muthusamy/globalpayments-woocommerce vendor. Now I have gateways.

**Comment by securesubmit-buildmaster** [comment]
@zxfrank We appreciate the feedback. We deploy this plugin to the [WordPress Plugin Directory](https://wordpress.org/plugins/global-payments-woocommerce/) with the `vendor` directory included for autoloading dependencies.

While we do not commit the `vendor` directory along with our source code here, the `composer.json` file should be included. We will work to include it here. Until we can make that happen, feel free to use the tagged versions of the plugin from the WordPress Plugin Directory.

Please let us know if you have any other questions/concerns.
