### ISSUE TITLE
I can't seem to process test payments on the frontend but I can process in the backend(wp-admin)

### ISSUE THREAD

**Issue by ericmuigai** [globalpayments/globalpayments-woocommerce#39]
"Status Code: INVALID_REQUEST_DATA - Format of one or more Data Elements is Invalid according to the Specification challenge_notification_url"
Is the error I get when testing.

**Comment by apetrovici** [comment]
Hi,

You are getting this error because your domain http://localhost is invalid. You can change it to http://localhost.dev or http://localhost.com.

**Comment by ericmuigai** [comment]
OK, let me do that.

**Comment by ericmuigai** [comment]
Hi,
Coming back to confirm it was indeed the issue.
Thank you.
